import React, { useMemo, useState } from 'react';
import { Activity, BrainCircuit, CalendarDays, Gauge, ShieldAlert, TrendingDown, TrendingUp } from 'lucide-react';
import { FreightLane, Port, Vessel } from '../../types';
import { mlForecastFreight } from '../../utils/mlFreightEngine';
import { validateFreightModels } from '../../utils/modelValidationEngine';

interface FreightForecastViewProps { freightLanes: FreightLane[]; ports?: Port[]; vessels?: Vessel[]; }

export const FreightForecastView: React.FC<FreightForecastViewProps> = ({ freightLanes, ports = [], vessels = [] }) => {
  const [selectedLaneId, setSelectedLaneId] = useState(freightLanes[0]?.id ?? '');
  const lane = freightLanes.find(item => item.id === selectedLaneId) ?? freightLanes[0];
  const result = useMemo(() => lane ? mlForecastFreight(lane, ports, vessels) : null, [lane, ports, vessels]);
  const validation = useMemo(() => lane ? validateFreightModels(lane, ports, vessels) : [], [lane, ports, vessels]);
  if (!lane || !result) return <div className="h-full bg-black text-gray-500 p-6">NO FREIGHT SERIES AVAILABLE</div>;
  const historical = lane.historicalRates ?? [];
  const values = historical.map(point => point.rate);
  const maxRate = Math.max(...values, result.currentRate, result.forecast7d, result.forecast14d, result.forecast30d) * 1.08;
  const minRate = Math.min(...values, result.currentRate, result.forecast7d, result.forecast14d, result.forecast30d) * 0.92;
  const range = Math.max(maxRate - minRate, 1);
  const charterWindow = result.direction === 'DOWN' ? 'WAIT / 7–14D' : result.direction === 'UP' ? 'CHARTER NOW / 0–7D' : 'MONITOR / 7–10D';
  const forecastValues = [result.forecast7d, result.forecast14d, result.forecast30d];
  return <div className="h-full overflow-auto bg-black text-[#d1d1d1] font-mono p-3">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#333] pb-2 mb-3"><div><div className="flex items-center gap-2 text-white font-bold text-sm"><BrainCircuit className="w-4 h-4 text-[#F27D26]"/>FREIGHT FORECAST ENGINE</div><div className="text-[10px] text-gray-500 mt-1">ML REGRESSION • CHRONOLOGICAL FIT • 7D / 14D / 30D HORIZONS</div></div><select value={selectedLaneId} onChange={e=>setSelectedLaneId(e.target.value)} className="bg-[#111] border border-[#444] text-white px-2 py-1 text-xs outline-none">{freightLanes.map(item=><option key={item.id} value={item.id}>{item.code} — {item.name}</option>)}</select></div>
    <div className="grid grid-cols-2 lg:grid-cols-7 gap-2 mb-3"><Metric label="CURRENT" value={`$${result.currentRate.toLocaleString()}`} sub={lane.rateUnit}/><Metric label="7D" value={`$${result.forecast7d.toFixed(0)}`} sub={`${result.change7dPct >= 0 ? '+' : ''}${result.change7dPct.toFixed(1)}%`}/><Metric label="14D" value={`$${result.forecast14d.toFixed(0)}`} sub={`${result.change14dPct >= 0 ? '+' : ''}${result.change14dPct.toFixed(1)}%`}/><Metric label="30D" value={`$${result.forecast30d.toFixed(0)}`} sub={`${result.change30dPct >= 0 ? '+' : ''}${result.change30dPct.toFixed(1)}%`}/><Metric label="DIRECTION" value={result.direction} icon={result.direction === 'UP' ? <TrendingUp className="w-4 h-4"/> : <TrendingDown className="w-4 h-4"/>}/><Metric label="CONFIDENCE" value={`${result.confidence.toFixed(0)}%`} icon={<Gauge className="w-4 h-4"/>}/><Metric label="VOLATILITY" value={`${result.volatilityPct.toFixed(2)}%`} icon={<Activity className="w-4 h-4"/>}/></div>
    <div className="grid lg:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)] gap-3">
      <section className="border border-[#333] bg-[#080808] p-3 min-h-[430px]"><div className="flex justify-between items-center mb-3"><span className="text-[#F27D26] font-bold text-xs">{lane.code} / ML RATE CURVE</span><span className="text-[9px] text-gray-500">ACTUAL + 7/14/30D PROJECTION</span></div><div className="relative h-[300px] border-l border-b border-[#333]"><div className="absolute inset-0 flex flex-col justify-between pointer-events-none">{[0,1,2,3,4].map(i=><div key={i} className="border-t border-[#181818] w-full"/>)}</div><svg viewBox="0 0 1000 300" preserveAspectRatio="none" className="absolute inset-0 w-full h-full"><polyline fill="none" stroke="#F27D26" strokeWidth="3" points={historical.map((point,index)=>{const x=historical.length===1?0:(index/Math.max(historical.length-1,1))*700;const y=300-(((point.rate-minRate)/range)*270)-15;return `${x},${y}`}).join(' ')}/><polyline fill="none" stroke="#00FF41" strokeWidth="2" strokeDasharray="8 6" points={forecastValues.map((value,index)=>{const x=700+(index/2)*300;const y=300-(((value-minRate)/range)*270)-15;return `${x},${y}`}).join(' ')}/></svg><div className="absolute left-2 top-2 text-[9px] text-gray-500">MAX ${maxRate.toFixed(0)}</div><div className="absolute left-2 bottom-2 text-[9px] text-gray-500">MIN ${minRate.toFixed(0)}</div></div><div className="flex gap-4 mt-2 text-[9px] text-gray-500"><span><i className="inline-block w-4 border-t-2 border-[#F27D26] mr-1 align-middle"/>HISTORICAL</span><span><i className="inline-block w-4 border-t-2 border-dashed border-[#00FF41] mr-1 align-middle"/>ML FORECAST</span></div></section>
      <section className="space-y-3"><div className="border border-[#333] bg-[#080808] p-3"><div className="text-[#F27D26] font-bold text-xs mb-2">MODEL DECISION</div><div className="text-white text-lg font-bold mb-2">{result.direction === 'UP' ? 'ACCUMULATE FREIGHT EXPOSURE' : result.direction === 'DOWN' ? 'DEFER CHARTER COMMITMENT' : 'HOLD / MONITOR'}</div><div className="text-[10px] text-gray-400 leading-relaxed">{result.modelName}. Confidence {result.confidence.toFixed(0)}%, historical volatility {result.volatilityPct.toFixed(2)}%. This is decision support, not a guaranteed market prediction.</div></div><div className="border border-[#333] bg-[#080808] p-3"><div className="flex items-center gap-2 text-[#00FF41] font-bold text-xs mb-2"><ShieldAlert className="w-3.5 h-3.5"/> SIH CHARTER SIGNAL</div><div className="grid grid-cols-2 gap-2 text-[10px]"><div className="bg-[#111] p-2"><span className="text-gray-500 block">WINDOW</span><span className="text-white">{charterWindow}</span></div><div className="bg-[#111] p-2"><span className="text-gray-500 block">CONGESTION</span><span className={lane.congestionIndex>=70?'text-red-400':'text-[#00FF41]'}>{lane.congestionIndex}/100</span></div><div className="bg-[#111] p-2"><span className="text-gray-500 block">VESSELS</span><span className="text-white">{lane.activeVessels}</span></div><div className="bg-[#111] p-2"><span className="text-gray-500 block">TRANSIT</span><span className="text-white">{lane.transitDays} days</span></div></div></div><div className="border border-[#333] bg-[#080808] p-3"><div className="text-[#F27D26] font-bold text-xs mb-2">EXPLAINABILITY</div>{result.featureContributions.map(item=><div key={item.feature} className="flex justify-between border-b border-[#222] py-1.5 text-[9px]"><span className="text-gray-500">{item.feature}</span><span className={item.impact>=0?'text-[#00FF41]':'text-red-400'}>{item.impact>=0?'+':''}{item.impact.toFixed(2)}</span></div>)}<div className="text-[9px] text-gray-600 mt-2">Samples {result.metrics.samples} • MAE {result.metrics.mae.toFixed(1)} • RMSE {result.metrics.rmse.toFixed(1)} • MAPE {result.metrics.mape.toFixed(1)}%</div></div></section>
    </div>
    <div className="mt-3 border border-[#333] bg-[#080808] p-3"><div className="flex items-center justify-between mb-2"><div className="flex items-center gap-2 text-[#F27D26] font-bold text-xs"><BrainCircuit className="w-3.5 h-3.5"/>MODEL VALIDATION</div><span className="text-[9px] text-gray-600">CHRONOLOGICAL 7D HOLDOUT</span></div><div className="overflow-x-auto"><div className="min-w-[760px] grid grid-cols-7 gap-px bg-[#333] text-[9px]"><div className="bg-[#111] p-2 text-gray-500">MODEL</div><div className="bg-[#111] p-2 text-gray-500">MAE</div><div className="bg-[#111] p-2 text-gray-500">RMSE</div><div className="bg-[#111] p-2 text-gray-500">MAPE</div><div className="bg-[#111] p-2 text-gray-500">DIRECTION HIT</div><div className="bg-[#111] p-2 text-gray-500">SAMPLES</div><div className="bg-[#111] p-2 text-gray-500">STATUS</div>{validation.map(row=><React.Fragment key={row.model}><div className="bg-[#080808] p-2 text-white">{row.model}</div><div className="bg-[#080808] p-2 text-gray-300">{row.samples ? row.mae.toFixed(2) : '—'}</div><div className="bg-[#080808] p-2 text-gray-300">{row.samples ? row.rmse.toFixed(2) : '—'}</div><div className="bg-[#080808] p-2 text-gray-300">{row.samples ? `${row.mape.toFixed(2)}%` : '—'}</div><div className="bg-[#080808] p-2 text-[#F27D26]">{row.samples ? `${row.directionHitPct.toFixed(0)}%` : '—'}</div><div className="bg-[#080808] p-2 text-gray-300">{row.samples || '—'}</div><div className="bg-[#080808] p-2 text-gray-500">{row.status}</div></React.Fragment>)}</div></div><div className="text-[9px] text-gray-600 mt-2">Python Gradient Boosting and Random Forest trainers are maintained offline in <span className="text-gray-400">ml/</span>. Their metrics are intentionally not fabricated in the browser; publish generated backtest_results.json only after running the training pipeline on the demo or approved historical dataset.</div></div>
    <div className="mt-3 border border-[#333] bg-[#080808] p-3"><div className="flex items-center gap-2 text-[#F27D26] font-bold text-xs mb-2"><CalendarDays className="w-3.5 h-3.5"/>HORIZON TABLE</div><div className="grid grid-cols-4 gap-px bg-[#333] text-[10px]"><div className="bg-[#111] p-2 text-gray-500">HORIZON</div><div className="bg-[#111] p-2 text-gray-500">FORECAST</div><div className="bg-[#111] p-2 text-gray-500">CHANGE</div><div className="bg-[#111] p-2 text-gray-500">IMPLICATION</div>{[['7D',result.forecast7d,result.change7dPct],['14D',result.forecast14d,result.change14dPct],['30D',result.forecast30d,result.change30dPct]].map(([h,v,c])=><React.Fragment key={String(h)}><div className="bg-[#080808] p-2 text-white">{h}</div><div className="bg-[#080808] p-2 text-white">${Number(v).toFixed(0)}</div><div className="bg-[#080808] p-2 text-[#F27D26]">{Number(c)>=0?'+':''}{Number(c).toFixed(1)}%</div><div className="bg-[#080808] p-2 text-gray-400">{Number(c)>1.5?'upside pressure':Number(c)<-1.5?'softer freight':'range-bound'}</div></React.Fragment>)}</div></div>
    <div className="text-[9px] text-gray-600 mt-3">MODEL VALIDATION: runtime chronological holdout plus an offline Python model-comparison pipeline. Production-grade accuracy requires real historical SIH freight observations and aligned external features.</div>
  </div>;
};

const Metric: React.FC<{ label:string; value:string; sub?:string; icon?:React.ReactNode }> = ({label,value,sub,icon}) => <div className="border border-[#333] bg-[#080808] p-2 min-h-[68px]"><div className="text-[9px] text-gray-500 mb-1">{label}</div><div className="text-white font-bold flex items-center gap-1">{icon}{value}</div>{sub&&<div className="text-[9px] text-[#F27D26] mt-1">{sub}</div>}</div>;
