import React, { useMemo, useState } from 'react';
import { Anchor, CheckCircle2, Ship, TriangleAlert } from 'lucide-react';
import { FreightLane, Vessel } from '../../types';
import { screenVessels } from '../../utils/vesselScreeningEngine';

export const VesselScreeningPanel: React.FC<{ lane: FreightLane; vessels: Vessel[] }> = ({ lane, vessels }) => {
  const [quantity, setQuantity] = useState(60000);
  const [laycan, setLaycan] = useState(14);
  const results = useMemo(() => screenVessels(lane, vessels, quantity, laycan), [lane, vessels, quantity, laycan]);
  return <section className="border border-[#333] bg-[#080808] p-3 mt-3 font-mono">
    <div className="flex flex-wrap items-center justify-between gap-2 mb-3"><div><div className="flex items-center gap-2 text-[#F27D26] font-bold text-xs"><Anchor className="w-3.5 h-3.5"/>AI VESSEL SCREEN</div><div className="text-[9px] text-gray-600 mt-1">CAPACITY • ROUTE • LAYCAN • PORT DRAFT • RISK</div></div><div className="flex gap-2"><label className="text-[9px] text-gray-500">CARGO MT <input type="number" min="1000" step="1000" value={quantity} onChange={e=>setQuantity(Number(e.target.value)||0)} className="ml-1 w-24 bg-[#111] border border-[#444] text-white px-2 py-1"/></label><label className="text-[9px] text-gray-500">LAYCAN DAYS <input type="number" min="1" max="60" value={laycan} onChange={e=>setLaycan(Number(e.target.value)||1)} className="ml-1 w-16 bg-[#111] border border-[#444] text-white px-2 py-1"/></label></div></div>
    <div className="text-[9px] text-gray-600 mb-2">SCREENING {lane.originPort} → {lane.destinationPort} • REQUIRED DWT {(quantity*1.08).toLocaleString()} • PROTOTYPE / DEMO AIS-LIKE FIXTURES</div>
    <div className="space-y-1">{results.slice(0,6).map((row, index)=><div key={row.vessel.id} className="grid grid-cols-[22px_1.6fr_.7fr_.7fr_.7fr_1fr] gap-2 items-center border border-[#222] bg-[#0b0b0b] px-2 py-2 text-[9px]"><div className="text-gray-600">{index+1}</div><div><div className="text-white font-bold"><Ship className="inline w-3 h-3 mr-1 text-[#F27D26]"/>{row.vessel.name}</div><div className="text-gray-600">{row.vessel.imo} • {row.vessel.operator}</div></div><div><span className="text-gray-600 block">SCORE</span><span className={row.score>=70?'text-[#00FF41]':row.score>=50?'text-amber-400':'text-red-400'}>{row.score.toFixed(0)}</span></div><div><span className="text-gray-600 block">DWT</span><span className="text-white">{row.vessel.dwt.toLocaleString()}</span></div><div><span className="text-gray-600 block">WAIT</span><span className="text-white">{row.vessel.congestionWaitHours}h</span></div><div className="flex items-center gap-1">{row.recommendation==='REJECT'?<TriangleAlert className="w-3 h-3 text-red-400"/>:<CheckCircle2 className="w-3 h-3 text-[#00FF41]"/>}<span className={row.recommendation==='PREFERRED'?'text-[#00FF41]':row.recommendation==='ALTERNATE'?'text-amber-400':'text-red-400'}>{row.recommendation}</span></div></div>)}</div>
    {results[0] && <div className="mt-3 grid lg:grid-cols-4 gap-2 text-[9px]">{[['CAPACITY FIT',results[0].capacityFit],['ROUTE FIT',results[0].routeFit],['TIMING FIT',results[0].timingFit],['PORT FIT',results[0].portFit]].map(([label,value])=><div key={String(label)} className="bg-[#111] border border-[#222] p-2"><span className="text-gray-600 block">{label}</span><span className="text-white font-bold">{Number(value).toFixed(0)}/100</span></div>)}</div>}
  </section>;
};
