import React, { useMemo, useState } from 'react';
import { Compass, Fuel, Ship, ShieldAlert } from 'lucide-react';
import { FreightLane, Vessel } from '../../types';

export const VesselIntelligenceView: React.FC<{ vessels: Vessel[]; freightLanes: FreightLane[] }> = ({ vessels, freightLanes }) => {
  const [type, setType] = useState('ALL');
  const [selected, setSelected] = useState(vessels[0]?.id ?? '');
  const filtered = useMemo(() => type === 'ALL' ? vessels : vessels.filter(v => v.type === type), [vessels, type]);
  const vessel = filtered.find(v => v.id === selected) ?? filtered[0] ?? vessels[0];
  if (!vessel) return <div className="h-full bg-black p-4 text-gray-500">NO VESSEL DATA</div>;
  const lane = freightLanes.find(l => l.id === vessel.currentLaneId);
  const fit = lane ? Math.max(0, Math.min(100, 55 + (vessel.dwt >= 50000 ? 20 : 5) - vessel.congestionWaitHours * 0.5 - (vessel.draftM > vessel.maxDraftM ? 30 : 0))) : 60;
  return <div className="h-full overflow-auto bg-black p-3 font-mono text-[#d1d1d1]"><div className="flex justify-between items-center border-b border-[#333] pb-2 mb-3"><div><div className="text-white font-bold text-sm"><Ship className="inline w-4 h-4 text-[#F27D26] mr-2"/>VESSEL INTELLIGENCE</div><div className="text-[9px] text-gray-500 mt-1">FLEET AVAILABILITY • CAPACITY • ETA • RISK • CARGO FIT</div></div><div className="flex gap-2"><select value={type} onChange={e=>setType(e.target.value)} className="bg-[#111] border border-[#444] text-white p-1 text-[10px]"><option value="ALL">ALL TYPES</option><option value="DRY_BULK">DRY BULK</option><option value="CRUDE_TANKER">CRUDE TANKER</option><option value="CONTAINER">CONTAINER</option><option value="LNG_CARRIER">LNG</option></select><select value={vessel.id} onChange={e=>setSelected(e.target.value)} className="bg-[#111] border border-[#444] text-white p-1 text-[10px]">{filtered.map(v=><option key={v.id} value={v.id}>{v.name} — {v.dwt.toLocaleString()} DWT</option>)}</select></div></div><div className="grid grid-cols-2 lg:grid-cols-6 gap-2 mb-3"><Metric l="VESSEL" v={vessel.name}/><Metric l="TYPE" v={vessel.type}/><Metric l="DWT" v={vessel.dwt.toLocaleString()}/><Metric l="DRAFT" v={`${vessel.draftM}m`}/><Metric l="ETA" v={vessel.eta}/><Metric l="FIT SCORE" v={`${fit.toFixed(0)}/100`} c={fit>=70?'text-[#00FF41]':fit>=50?'text-amber-400':'text-red-400'}/></div><div className="grid lg:grid-cols-[1.4fr_1fr] gap-3"><section className="border border-[#333] bg-[#080808] p-3"><div className="text-[#F27D26] font-bold text-xs mb-3">VESSEL PROFILE</div><div className="grid grid-cols-2 gap-2 text-[10px]"><Cell l="IMO / MMSI" v={`${vessel.imo} / ${vessel.mmsi}`}/><Cell l="OPERATOR" v={vessel.operator}/><Cell l="FLAG" v={vessel.flag}/><Cell l="STATUS" v={vessel.cargoStatus}/><Cell l="ROUTE" v={`${vessel.originPort} → ${vessel.destinationPort}`}/><Cell l="SPEED" v={`${vessel.speedKnots} kn`}/><Cell l="WAIT" v={`${vessel.congestionWaitHours} hours`}/><Cell l="CO₂ INTENSITY" v={`${vessel.co2PerTonNm} g/t-nm`}/></div></section><section className="border border-[#333] bg-[#080808] p-3"><div className="text-[#F27D26] font-bold text-xs mb-2">CHARTER SCREEN</div><div className="space-y-2 text-[10px]"><div className="p-2 bg-[#111]"><Compass className="inline w-3 h-3 mr-1 text-[#F27D26]"/>CURRENT LANE: <span className="text-white">{lane?.code ?? vessel.currentLaneId}</span></div><div className="p-2 bg-[#111]"><Fuel className="inline w-3 h-3 mr-1 text-[#F27D26]"/>CARGO CAPACITY: <span className="text-white">{vessel.dwt.toLocaleString()} DWT</span></div><div className="p-2 bg-[#111]"><ShieldAlert className="inline w-3 h-3 mr-1 text-[#F27D26]"/>RISK: <span className={vessel.riskAlert?'text-red-400':'text-[#00FF41]'}>{vessel.riskAlert ?? 'NO ACTIVE ALERT'}</span></div></div></section></div></div>;
};
const Metric=({l,v,c='text-white'}:{l:string;v:string;c?:string})=><div className="border border-[#333] bg-[#080808] p-2"><div className="text-[9px] text-gray-500">{l}</div><div className={`font-bold mt-1 truncate ${c}`}>{v}</div></div>;
const Cell=({l,v}:{l:string;v:string})=><div className="bg-[#111] p-2"><div className="text-gray-500">{l}</div><div className="text-white mt-1">{v}</div></div>;
