import React, { useMemo } from 'react';
import { AlertTriangle, TrendingDown, TrendingUp } from 'lucide-react';
import { Port } from '../../types';
import { rankPortCongestion } from '../../utils/congestionPredictionEngine';

export const CongestionForecastPanel: React.FC<{ ports: Port[] }> = ({ ports }) => {
  const rows = useMemo(() => rankPortCongestion(ports), [ports]);
  return <section className="border border-[#333] bg-[#080808] p-3 mt-3"><div className="flex items-center justify-between mb-3"><div><div className="flex items-center gap-2 text-[#F27D26] font-bold text-xs"><AlertTriangle className="w-3.5 h-3.5"/>PORT CONGESTION FORECAST</div><div className="text-[9px] text-gray-600 mt-1">7D / 14D OPERATIONAL PRESSURE MODEL • QUEUE • WAIT • STRUCTURAL RISK</div></div><span className="text-[9px] text-gray-600">PROTOTYPE</span></div><div className="overflow-x-auto"><div className="min-w-[760px] grid grid-cols-[.4fr_1.3fr_.7fr_.7fr_.7fr_.7fr_1.5fr] gap-px bg-[#333] text-[9px]"><div className="bg-[#111] p-2 text-gray-600">#</div><div className="bg-[#111] p-2 text-gray-600">PORT</div><div className="bg-[#111] p-2 text-gray-600">CURRENT</div><div className="bg-[#111] p-2 text-gray-600">7D</div><div className="bg-[#111] p-2 text-gray-600">14D</div><div className="bg-[#111] p-2 text-gray-600">TREND</div><div className="bg-[#111] p-2 text-gray-600">ACTION</div>{rows.map((row,index)=><React.Fragment key={row.port.id}><div className="bg-[#080808] p-2 text-gray-600">{index+1}</div><div className="bg-[#080808] p-2 text-white font-bold">{row.port.code} <span className="text-gray-600 font-normal">{row.port.name}</span></div><div className="bg-[#080808] p-2 text-white">{row.currentScore}</div><div className="bg-[#080808] p-2 text-[#F27D26]">{row.forecast7d.toFixed(0)}</div><div className="bg-[#080808] p-2 text-[#F27D26]">{row.forecast14d.toFixed(0)}</div><div className="bg-[#080808] p-2">{row.direction === 'WORSENING' ? <span className="text-red-400"><TrendingUp className="inline w-3 h-3 mr-1"/>WORSENING</span> : row.direction === 'IMPROVING' ? <span className="text-[#00FF41]"><TrendingDown className="inline w-3 h-3 mr-1"/>IMPROVING</span> : <span className="text-gray-400">STABLE</span>}</div><div className="bg-[#080808] p-2 text-gray-400">{row.action}</div></React.Fragment>)}</div></div><div className="text-[9px] text-gray-600 mt-3">Forecast is a transparent operational pressure model using current queue, wait and optional weather history. It is not an official port-authority forecast.</div></section>;
};
