import React, { useMemo, useState } from 'react';
import { Anchor, ArrowDownRight, ArrowRight, ArrowUpRight, BarChart3, BrainCircuit, CheckCircle2, Gauge, PackageSearch, RefreshCw, Ship, Sparkles, Target, TrendingDown, TrendingUp, Zap } from 'lucide-react';
import { FreightLane, Port, Vessel } from '../../types';
import { mlForecastFreight } from '../../utils/mlFreightEngine';
import { buildCharterRecommendation } from '../../utils/charterEngine';
import { buildProcurementRecommendation } from '../../utils/procurementEngine';
import { calculateFreightOpportunity } from '../../utils/freightOpportunityEngine';
import { buildIntegratedDecision } from '../../utils/integratedDecisionEngine';
import { IntegratedDecisionPanel } from '../Charter/IntegratedDecisionPanel';
import { ScenarioAnalysisPanel } from './ScenarioAnalysisPanel';

interface Props {
  freightLanes: FreightLane[];
  ports: Port[];
  vessels: Vessel[];
  onNavigateView: (view: 'FCST' | 'PORT' | 'VSL' | 'PROC' | 'CHART') => void;
}

type Horizon = 7 | 14 | 30;
type Focus = 'decision' | 'freight' | 'port' | 'vessel' | 'procurement';

const money = (value: number, digits = 2) => `$${value.toLocaleString(undefined, { minimumFractionDigits: digits, maximumFractionDigits: digits })}`;
const riskTone = (value: number) => value >= 70 ? 'text-red-400' : value >= 50 ? 'text-[#F27D26]' : 'text-[#00FF41]';

export const SIHCommandCenterCockpit: React.FC<Props> = ({ freightLanes, ports, vessels, onNavigateView }) => {
  const filtered = freightLanes.filter(lane => lane.type === 'DRY_BULK' && (lane.name.toLowerCase().includes('india') || ['INPAR', 'INVIS', 'INDHM', 'INGAN'].includes(lane.destinationPort)));
  const lanes = filtered.length ? filtered : freightLanes.filter(lane => lane.type === 'DRY_BULK').slice(0, 6);
  const [laneId, setLaneId] = useState(lanes[0]?.id ?? '');
  const [quantity, setQuantity] = useState(60000);
  const [laycan, setLaycan] = useState(14);
  const [horizon, setHorizon] = useState<Horizon>(30);
  const [focus, setFocus] = useState<Focus>('decision');
  const [refresh, setRefresh] = useState(0);

  const lane = lanes.find(item => item.id === laneId) ?? lanes[0];
  const forecast = useMemo(() => lane ? mlForecastFreight(lane, ports, vessels) : null, [lane, ports, vessels, refresh]);
  const charter = useMemo(() => lane ? buildCharterRecommendation({ laneId: lane.id, cargoType: lane.type, quantityMt: quantity, laycanDays: laycan }, freightLanes, ports, vessels) : null, [lane, quantity, laycan, freightLanes, ports, vessels]);
  const procurement = useMemo(() => lane ? buildProcurementRecommendation(lane.type === 'CRUDE' ? 'CRUDE' : lane.type === 'LNG' ? 'LNG' : 'DRY_BULK', quantity, [lane], ports, lane.destinationPort) : null, [lane, quantity, ports]);
  const integrated = useMemo(() => lane ? buildIntegratedDecision(lane, ports, vessels, quantity, laycan) : null, [lane, ports, vessels, quantity, laycan]);
  const opportunity = useMemo(() => lane && forecast ? calculateFreightOpportunity(lane, forecast, quantity) : null, [lane, forecast, quantity]);

  if (!lane || !forecast || !integrated || !procurement || !opportunity) return <div className="h-full bg-black text-gray-500 p-6">NO SIH DRY-BULK DATA AVAILABLE</div>;

  const destination = ports.find(port => port.code === lane.destinationPort);
  const topVessel = integrated.vessels[0] ?? charter?.matches[0];
  const rate = horizon === 7 ? forecast.forecast7d : horizon === 14 ? forecast.forecast14d : forecast.forecast30d;
  const change = ((rate - forecast.currentRate) / Math.max(forecast.currentRate, 0.01)) * 100;
  const signal = change >= 1.5 ? 'UP' : change <= -1.5 ? 'DOWN' : 'FLAT';
  const action = integrated.action;
  const actionText = action === 'FIX NOW' ? 'SECURE FREIGHT' : action === 'SPLIT' ? 'SPLIT EXPOSURE' : action === 'WAIT' ? 'WAIT FOR WINDOW' : 'WATCH MARKET';
  const portRisk = Math.round(integrated.congestion.forecast14d);
  const currentFreight = forecast.currentRate * quantity;
  const modelledFreight = rate * quantity;
  const impact = Math.abs(modelledFreight - currentFreight);
  const history = lane.historicalRates.slice(-20).map(item => ({ label: item.date.slice(5), value: item.rate }));
  const chart = [...history, { label: '7D', value: forecast.forecast7d }, { label: '14D', value: forecast.forecast14d }, { label: '30D', value: forecast.forecast30d }];
  const min = Math.min(...chart.map(point => point.value)) * 0.96;
  const max = Math.max(...chart.map(point => point.value)) * 1.04;
  const chartPoints = chart.map((point, index) => ({ ...point, x: 24 + (index / Math.max(chart.length - 1, 1)) * 650, y: 170 - ((point.value - min) / Math.max(max - min, 0.01)) * 125, forecast: index >= history.length }));
  const linePath = chartPoints.map((point, index) => `${index ? 'L' : 'M'} ${point.x.toFixed(1)} ${point.y.toFixed(1)}`).join(' ');
  const forecastPath = chartPoints.slice(Math.max(history.length - 1, 0)).map((point, index) => `${index ? 'L' : 'M'} ${point.x.toFixed(1)} ${point.y.toFixed(1)}`).join(' ');

  const chooseChartHorizon = (label: string) => {
    if (label === '7D' || label === '14D' || label === '30D') setHorizon(Number(label.replace('D', '')) as Horizon);
  };

  return <div className="h-full overflow-auto bg-[#020202] text-[#d4d4d4] font-mono p-3 md:p-4">
    <div className="max-w-[1700px] mx-auto space-y-3">
      <header className="border border-[#303030] bg-[#070707] shadow-[0_0_45px_rgba(242,125,38,0.07)]">
        <div className="px-4 py-3 flex flex-wrap items-center justify-between gap-3 border-b border-[#252525]">
          <div><div className="flex items-center gap-2 text-white text-lg font-black tracking-tight"><span className="text-[#F27D26]">◉</span> SIH COMMAND CENTER <span className="border border-[#315e3d] text-[#5ee58b] px-2 py-1 text-[8px] tracking-widest">DECISION COCKPIT</span></div><div className="text-[9px] text-gray-500 mt-1">SIH26006 • EAST COAST INDIA • CARGO → FREIGHT → PORT → VESSEL → PROCUREMENT → CHARTER</div></div>
          <div className="flex items-center gap-2 text-[8px]"><span className="border border-[#244d31] bg-[#09130c] text-[#5ee58b] px-2 py-1">● MODEL ACTIVE</span><span className="border border-[#24404a] bg-[#061014] text-cyan-300 px-2 py-1">● AIS DEMO</span><button onClick={() => setRefresh(value => value + 1)} className="border border-[#444] hover:border-[#F27D26] px-2 py-1 text-gray-400 hover:text-white transition-colors"><RefreshCw className="inline w-3 h-3 mr-1"/>RECALCULATE</button></div>
        </div>
        <div className="p-4 grid lg:grid-cols-[1fr_1.7fr_1fr] gap-4 items-end">
          <Field label="CARGO REQUIREMENT"><div className="flex gap-2 items-center"><input aria-label="Cargo quantity in metric tons" type="number" min={1000} step={1000} value={quantity} onChange={event => setQuantity(Math.max(1000, Number(event.target.value) || 1000))} className="w-36 bg-black border border-[#555] focus:border-[#F27D26] outline-none text-white text-lg font-black px-3 py-2"/><span className="text-[9px] text-gray-500">METRIC TONS</span></div><input aria-label="Cargo quantity slider" type="range" min={10000} max={150000} step={5000} value={quantity} onChange={event => setQuantity(Number(event.target.value))} className="w-full mt-2 accent-[#F27D26]"/><div className="flex justify-between text-[7px] text-gray-600"><span>10K</span><span>150K MT</span></div></Field>
          <Field label="EAST COAST PROCUREMENT LANE"><select aria-label="East Coast procurement lane" value={lane.id} onChange={event => setLaneId(event.target.value)} className="w-full bg-black border border-[#555] focus:border-[#F27D26] outline-none text-white text-sm px-3 py-2">{lanes.map(item => <option key={item.id} value={item.id}>{item.code} — {item.originPort} → {item.destinationPort}</option>)}</select><div className="flex items-center gap-2 mt-2 text-[8px] text-gray-500"><span className="text-[#F27D26]">●</span>{lane.name}<span className="ml-auto">{lane.distanceNm.toLocaleString()} NM</span></div></Field>
          <Field label="LAYCAN WINDOW"><div className="grid grid-cols-4 gap-1">{[7, 14, 21, 30].map(days => <button key={days} onClick={() => setLaycan(days)} className={`py-2 text-[9px] font-bold border ${laycan === days ? 'bg-[#F27D26] text-black border-[#F27D26]' : 'bg-[#0d0d0d] text-gray-500 border-[#333] hover:text-white'}`}>{days}D</button>)}</div><div className="text-[8px] text-gray-600 mt-2">VESSEL ARRIVAL WINDOW: {laycan} DAYS</div></Field>
        </div>
      </header>

      <div className="grid grid-cols-2 lg:grid-cols-6 gap-2">
        <Kpi label="SPOT FREIGHT" value={money(forecast.currentRate)} sub="CURRENT $/MT" tone="neutral" onClick={() => setFocus('freight')} />
        <Kpi label={`${horizon}D FORECAST`} value={money(rate)} sub={`${change >= 0 ? '+' : ''}${change.toFixed(1)}%`} tone={signal === 'UP' ? 'red' : signal === 'DOWN' ? 'green' : 'amber'} onClick={() => setFocus('freight')} />
        <Kpi label="MARKET SIGNAL" value={signal} sub={signal === 'UP' ? 'RISING PRESSURE' : signal === 'DOWN' ? 'FALLING PRESSURE' : 'NEUTRAL RANGE'} tone={signal === 'UP' ? 'red' : signal === 'DOWN' ? 'green' : 'amber'} icon={signal === 'UP' ? <TrendingUp/> : signal === 'DOWN' ? <TrendingDown/> : <ArrowRight/>} onClick={() => setFocus('freight')} />
        <Kpi label="DECISION CONFIDENCE" value={`${integrated.confidence.toFixed(0)}%`} sub="INTEGRATED STACK" tone="cyan" icon={<Gauge/>} onClick={() => setFocus('decision')} />
        <Kpi label="PORT RISK / 14D" value={`${portRisk}/100`} sub={`${integrated.congestion.delayDays.toFixed(1)}D DELAY`} tone={portRisk >= 70 ? 'red' : portRisk >= 50 ? 'amber' : 'green'} icon={<Anchor/>} onClick={() => setFocus('port')} />
        <Kpi label="RECOMMENDED ACTION" value={action} sub={actionText} tone={action === 'FIX NOW' ? 'red' : action === 'WAIT' ? 'green' : 'amber'} icon={<Zap/>} onClick={() => setFocus('decision')} />
      </div>

      <div className="grid xl:grid-cols-[1.7fr_0.85fr] gap-3">
        <section className="border border-[#303030] bg-[#070707] overflow-hidden">
          <div className="px-4 py-3 border-b border-[#252525] flex flex-wrap justify-between gap-3 items-center"><div><div className="flex gap-2 items-center text-white font-bold text-sm"><BarChart3 className="w-4 h-4 text-[#F27D26]"/> FREIGHT INTELLIGENCE</div><div className="text-[8px] text-gray-600 mt-1">ACTUAL LANE HISTORY → MODEL FORECAST • CLICK A FORECAST POINT</div></div><div className="flex gap-1 bg-black border border-[#292929] p-1">{([7, 14, 30] as Horizon[]).map(days => <button key={days} onClick={() => setHorizon(days)} className={`px-4 py-1.5 text-[9px] font-black ${horizon === days ? 'bg-[#F27D26] text-black' : 'text-gray-500 hover:text-white'}`}>{days}D</button>)}</div></div>
          <div className="p-3"><div className="flex flex-wrap items-end justify-between gap-4 mb-2"><div><div className="text-[8px] text-gray-600">SELECTED MODEL WINDOW</div><div className="text-3xl text-white font-black">{money(rate)}<span className="text-[9px] text-gray-600 ml-2">/ MT</span></div></div><div className={`text-right ${signal === 'UP' ? 'text-red-400' : signal === 'DOWN' ? 'text-[#00FF41]' : 'text-[#F27D26]'}`}><div className="text-2xl font-black">{change >= 0 ? '+' : ''}{change.toFixed(1)}%</div><div className="text-[8px] text-gray-600">VS CURRENT FREIGHT</div></div></div><div className="h-[270px] w-full"><svg viewBox="0 0 700 205" className="w-full h-full" role="img" aria-label="Interactive freight history and forecast chart">{[45, 90, 135, 180].map(y => <line key={y} x1="24" x2="675" y1={y} y2={y} stroke="#1b1b1b"/>)}<line x1={chartPoints[history.length - 1]?.x ?? 0} x2={chartPoints[history.length - 1]?.x ?? 0} y1="20" y2="182" stroke="#F27D26" strokeDasharray="3 4" opacity="0.45"/><path d={linePath} fill="none" stroke="#cfcfcf" strokeWidth="2"/><path d={forecastPath} fill="none" stroke="#F27D26" strokeWidth="3" strokeDasharray="7 5"/>{chartPoints.map((point, index) => <g key={`${point.label}-${index}`} onClick={() => point.forecast && chooseChartHorizon(point.label)} className={point.forecast ? 'cursor-pointer' : ''}><circle cx={point.x} cy={point.y} r={point.forecast ? 6 : 2.5} fill={point.forecast ? '#F27D26' : '#d1d1d1'}/>{point.forecast && <text x={point.x} y={point.y - 10} textAnchor="middle" fill={point.label === `${horizon}D` ? '#fff' : '#777'} fontSize="8" fontWeight="bold">{point.label}</text>}</g>)}</svg></div><div className="flex flex-wrap gap-4 text-[8px] text-gray-600"><span>● HISTORY</span><span className="text-[#F27D26]">● FORECAST</span><span className="ml-auto">{forecast.modelName} • {forecast.confidence.toFixed(0)}% MODEL CONFIDENCE</span></div></div>
        </section>

        <section className="border border-[#F27D26] bg-[#090705] shadow-[0_0_35px_rgba(242,125,38,0.08)]"><div className="px-4 py-3 border-b border-[#292929] flex justify-between items-center"><div><div className="flex gap-2 items-center text-white text-sm font-black"><BrainCircuit className="w-4 h-4 text-[#F27D26]"/> DECISION ENGINE</div><div className="text-[8px] text-gray-600 mt-1">FOUR SIGNALS → ONE ACTION</div></div><div className="text-right"><div className="text-[7px] text-gray-600">STACK SCORE</div><div className="text-[#F27D26] font-black">{integrated.score.toFixed(0)}<span className="text-gray-700">/100</span></div></div></div><div className="p-4"><div className="flex justify-between items-end gap-3"><div><div className="text-[8px] text-gray-600">RECOMMENDED ACTION</div><div className={`text-3xl font-black mt-1 ${action === 'FIX NOW' ? 'text-red-400' : action === 'WAIT' ? 'text-[#00FF41]' : 'text-[#F27D26]'}`}>{action}</div><div className="text-[8px] text-gray-500 mt-1">{actionText}</div></div><div className="text-right"><div className="text-[8px] text-gray-600">CONFIDENCE</div><div className="text-2xl text-white font-black">{integrated.confidence.toFixed(0)}%</div></div></div><Meter value={integrated.score}/><div className="grid grid-cols-4 text-[7px] text-gray-600 mt-1"><span>WAIT</span><span className="text-center">WATCH</span><span className="text-center">SPLIT</span><span className="text-right">FIX NOW</span></div><div className="grid grid-cols-2 gap-2 mt-4">{integrated.factors.map(factor => <button key={factor.label} onClick={() => setFocus(factor.label.toLowerCase().includes('freight') ? 'freight' : factor.label.toLowerCase().includes('port') ? 'port' : factor.label.toLowerCase().includes('vessel') ? 'vessel' : 'procurement')} className="text-left border border-[#242424] bg-[#0c0c0c] hover:border-[#F27D26] p-2 transition-colors"><div className="flex justify-between text-[7px] text-gray-600"><span>{factor.label.toUpperCase()}</span><span>{factor.weight}%</span></div><div className={factor.value >= 0 ? 'text-[#00FF41] font-black mt-1' : 'text-red-400 font-black mt-1'}>{factor.value >= 0 ? '+' : ''}{factor.value.toFixed(1)}</div><div className="text-[7px] text-gray-600 mt-1 leading-relaxed">{factor.interpretation}</div></button>)}</div></div></section>
      </div>

      <section className="border border-[#303030] bg-[#070707]"><div className="px-4 py-3 border-b border-[#252525] flex items-center justify-between"><div className="flex gap-2 items-center text-white text-sm font-black"><Target className="w-4 h-4 text-[#F27D26]"/> DECISION CHAIN</div><div className="text-[8px] text-gray-600">CLICK A STAGE — INSPECTOR RESPONDS</div></div><div className="p-3 grid md:grid-cols-5 gap-2"><Chain step="01" title="CARGO" value={`${quantity.toLocaleString()} MT`} detail="Requirement" active={focus === 'procurement'} icon={<PackageSearch/>} onClick={() => setFocus('procurement')}/><Chain step="02" title="FREIGHT" value={`${money(forecast.currentRate)} → ${money(rate)}`} detail={`${horizon}D ${change >= 0 ? '+' : ''}${change.toFixed(1)}%`} active={focus === 'freight'} icon={signal === 'DOWN' ? <ArrowDownRight/> : <ArrowUpRight/>} onClick={() => setFocus('freight')}/><Chain step="03" title="PORT" value={`${portRisk}/100`} detail={`${integrated.congestion.delayDays.toFixed(1)}D delay`} active={focus === 'port'} icon={<Anchor/>} onClick={() => setFocus('port')}/><Chain step="04" title="VESSEL" value={topVessel?.vessel.name ?? 'NO MATCH'} detail={topVessel ? `${topVessel.score.toFixed(0)}/100 • ${topVessel.vessel.dwt.toLocaleString()} DWT` : 'Capacity screen'} active={focus === 'vessel'} icon={<Ship/>} onClick={() => setFocus('vessel')}/><Chain step="05" title="DECISION" value={action} detail={actionText} active={focus === 'decision'} icon={<Zap/>} onClick={() => setFocus('decision')}/></div></section>

      <Inspector focus={focus} lane={lane} forecast={forecast} integrated={integrated} procurement={procurement} topVessel={topVessel} destination={destination} portRisk={portRisk} quantity={quantity} horizon={horizon} change={change} rate={rate} onNavigateView={onNavigateView}/>

      <div className="grid lg:grid-cols-2 gap-3"><IntegratedDecisionPanel lane={lane} ports={ports} vessels={vessels} quantityMt={quantity} laycanDays={laycan}/><ScenarioAnalysisPanel lane={lane} ports={ports} vessels={vessels} quantityMt={quantity}/></div>

      <section className="border border-[#F27D26] bg-[#100b07] p-4 shadow-[0_0_35px_rgba(242,125,38,0.05)]"><div className="flex flex-wrap justify-between gap-3 items-end"><div><div className="text-[#F27D26] text-sm font-black">FREIGHT ECONOMIC IMPACT</div><div className="text-[8px] text-gray-600 mt-1">{quantity.toLocaleString()} MT × selected {horizon}D modelled rate</div></div><div className="text-right"><div className="text-[7px] text-gray-600">{opportunity.direction === 'BUY_NOW' ? 'EXPOSURE IF DELAYED' : opportunity.direction === 'WAIT' ? 'POTENTIAL SAVING' : 'MODELLED IMPACT'}</div><div className="text-3xl text-white font-black">{money(impact, 0)}</div></div></div><div className="grid md:grid-cols-3 gap-2 mt-4"><Economic label="CURRENT FREIGHT" value={money(currentFreight, 0)}/><Economic label={`${horizon}D MODELLED`} value={money(modelledFreight, 0)}/><Economic label="RATE DELTA" value={`${change >= 0 ? '+' : '-'}${money(Math.abs(rate - forecast.currentRate))}/MT`}/></div><div className="text-[8px] text-gray-600 mt-3">{opportunity.explanation} Modelled decision support only; excludes commodity price, financing, demurrage and execution effects.</div></section>

      <footer className="flex flex-wrap justify-between gap-2 text-[7px] text-gray-700 py-2"><span>DEMO / DECISION-SUPPORT DATA • NO LIVE BROKER QUOTE OR CHARTER EXECUTION</span><span>CHANGE CARGO, LANE, LAYCAN OR HORIZON — THE DECISION STACK RESPONDS.</span></footer>
    </div>
  </div>;
};

const Field: React.FC<{ label: string; children: React.ReactNode }> = ({ label, children }) => <div><div className="text-[8px] text-gray-600 mb-1 tracking-widest">{label}</div>{children}</div>;
const Meter: React.FC<{ value: number }> = ({ value }) => <div className="h-2 bg-[#181818] mt-4 overflow-hidden"><div className="h-full bg-[#F27D26] transition-all duration-500" style={{ width: `${Math.max(0, Math.min(100, value))}%` }}/></div>;
const Kpi: React.FC<{ label: string; value: string; sub: string; tone: 'neutral' | 'green' | 'red' | 'amber' | 'cyan'; icon?: React.ReactNode; onClick: () => void }> = ({ label, value, sub, tone, icon, onClick }) => { const color = tone === 'green' ? 'text-[#00FF41]' : tone === 'red' ? 'text-red-400' : tone === 'cyan' ? 'text-cyan-300' : tone === 'amber' ? 'text-[#F27D26]' : 'text-white'; return <button onClick={onClick} className="text-left border border-[#292929] bg-[#080808] hover:border-[#F27D26] hover:-translate-y-0.5 transition-all p-3 min-h-[94px]"><div className="flex justify-between text-[8px] text-gray-600"><span>{label}</span>{icon}</div><div className={`text-xl font-black mt-2 ${color}`}>{value}</div><div className="text-[7px] text-gray-700 mt-1">{sub}</div></button>; };
const Chain: React.FC<{ step: string; title: string; value: string; detail: string; icon: React.ReactNode; active: boolean; onClick: () => void }> = ({ step, title, value, detail, icon, active, onClick }) => <button onClick={onClick} className={`text-left border p-3 transition-all ${active ? 'border-[#F27D26] bg-[#120d08] shadow-[inset_3px_0_0_#F27D26]' : 'border-[#292929] bg-[#0b0b0b] hover:border-[#555]'}`}><div className="flex justify-between"><span className="text-[7px] text-gray-700">{step}</span><span className="text-[#F27D26]">{icon}</span></div><div className="text-[8px] text-gray-600 mt-2">{title}</div><div className="text-white text-sm font-black mt-1 truncate">{value}</div><div className="text-[7px] text-gray-700 mt-1">{detail}</div></button>;
const Economic: React.FC<{ label: string; value: string }> = ({ label, value }) => <div className="border border-[#2c1d12] bg-[#0b0806] p-3"><div className="text-[7px] text-gray-600">{label}</div><div className="text-white font-black mt-1">{value}</div></div>;

const Inspector: React.FC<{ focus: Focus; lane: FreightLane; forecast: ReturnType<typeof mlForecastFreight>; integrated: ReturnType<typeof buildIntegratedDecision>; procurement: ReturnType<typeof buildProcurementRecommendation>; topVessel: ReturnType<typeof buildIntegratedDecision>['vessels'][number] | undefined; destination?: Port; portRisk: number; quantity: number; horizon: Horizon; change: number; rate: number; onNavigateView: Props['onNavigateView'] }> = ({ focus, lane, forecast, integrated, procurement, topVessel, destination, portRisk, quantity, horizon, change, rate, onNavigateView }) => {
  const title = focus === 'freight' ? 'FREIGHT SIGNAL' : focus === 'port' ? 'PORT PRESSURE' : focus === 'vessel' ? 'VESSEL FIT' : focus === 'procurement' ? 'PROCUREMENT WINDOW' : 'DECISION RATIONALE';
  return <section className="border border-[#303030] bg-[#070707] overflow-hidden"><div className="px-4 py-3 border-b border-[#252525] flex items-center justify-between"><div><div className="text-white text-sm font-black">LIVE INSPECTOR — {title}</div><div className="text-[7px] text-gray-600 mt-1">THIS PANEL REACTS TO YOUR CURRENT INPUTS</div></div><Sparkles className="w-4 h-4 text-[#F27D26]"/></div><div className="p-4">{focus === 'freight' && <FreightInspector forecast={forecast} horizon={horizon} change={change} rate={rate} onNavigate={() => onNavigateView('FCST')}/>} {focus === 'port' && <PortInspector lane={lane} destination={destination} risk={portRisk} integrated={integrated} onNavigate={() => onNavigateView('PORT')}/>} {focus === 'vessel' && <VesselInspector topVessel={topVessel} quantity={quantity} onNavigate={() => onNavigateView('VSL')}/>} {focus === 'procurement' && <ProcurementInspector procurement={procurement} quantity={quantity} onNavigate={() => onNavigateView('PROC')}/>} {focus === 'decision' && <DecisionInspector integrated={integrated} lane={lane} quantity={quantity} onNavigate={() => onNavigateView('CHART')}/>}</div></section>;
};

const FreightInspector: React.FC<{ forecast: ReturnType<typeof mlForecastFreight>; horizon: Horizon; change: number; rate: number; onNavigate: () => void }> = ({ forecast, horizon, change, rate, onNavigate }) => <div className="grid lg:grid-cols-[1fr_auto] gap-4 items-center"><div><div className="text-4xl font-black text-white">{rate.toFixed(2)} <span className="text-[9px] text-gray-600">$/MT</span></div><div className={`text-sm font-black mt-1 ${change >= 1.5 ? 'text-red-400' : change <= -1.5 ? 'text-[#00FF41]' : 'text-[#F27D26]'}`}>{change >= 0 ? '+' : ''}{change.toFixed(1)}% over {horizon} days</div><div className="text-[8px] text-gray-600 mt-3">Model confidence {forecast.confidence.toFixed(0)}% • MAE {forecast.metrics.mae.toFixed(1)} • MAPE {forecast.metrics.mape.toFixed(1)}%</div></div><button onClick={onNavigate} className="border border-[#333] hover:border-[#F27D26] text-[#F27D26] px-4 py-3 text-[9px] font-bold">OPEN FREIGHT FORECAST →</button></div>;
const PortInspector: React.FC<{ lane: FreightLane; destination?: Port; risk: number; integrated: ReturnType<typeof buildIntegratedDecision>; onNavigate: () => void }> = ({ lane, destination, risk, integrated, onNavigate }) => <div className="grid lg:grid-cols-[1fr_1fr_auto] gap-3 items-center"><div><div className={`text-4xl font-black ${riskTone(risk)}`}>{risk}<span className="text-[9px] text-gray-600">/100</span></div><div className="text-[8px] text-gray-600 mt-1">14D PROJECTED CONGESTION</div></div><div className="grid grid-cols-2 gap-2"><Box label="DESTINATION" value={destination?.name ?? lane.destinationPort}/><Box label="WAIT" value={destination ? `${destination.avgWaitDays.toFixed(1)}D` : '—'}/><Box label="VESSELS WAITING" value={destination ? `${destination.vesselsWaiting}` : '—'}/><Box label="INDICATIVE DELAY" value={`${integrated.congestion.delayDays.toFixed(1)}D`}/></div><button onClick={onNavigate} className="border border-[#333] hover:border-[#F27D26] text-[#F27D26] px-4 py-3 text-[9px] font-bold">OPEN PORT INTEL →</button></div>;
const VesselInspector: React.FC<{ topVessel: ReturnType<typeof buildIntegratedDecision>['vessels'][number] | undefined; quantity: number; onNavigate: () => void }> = ({ topVessel, quantity, onNavigate }) => <div className="grid lg:grid-cols-[1fr_1fr_auto] gap-3 items-center"><div><div className="text-2xl text-white font-black">{topVessel?.vessel.name ?? 'NO MATCH'}</div><div className="text-[8px] text-gray-600 mt-1">BEST FIT FOR {quantity.toLocaleString()} MT</div></div><div className="grid grid-cols-3 gap-2"><Box label="FIT" value={topVessel ? `${topVessel.score.toFixed(0)}/100` : '—'}/><Box label="DWT" value={topVessel ? topVessel.vessel.dwt.toLocaleString() : '—'}/><Box label="WAIT" value={topVessel ? `${topVessel.vessel.congestionWaitHours.toFixed(0)}H` : '—'}/></div><button onClick={onNavigate} className="border border-[#333] hover:border-[#F27D26] text-[#F27D26] px-4 py-3 text-[9px] font-bold">OPEN VESSEL SCREEN →</button></div>;
const ProcurementInspector: React.FC<{ procurement: ReturnType<typeof buildProcurementRecommendation>; quantity: number; onNavigate: () => void }> = ({ procurement, quantity, onNavigate }) => <div className="grid lg:grid-cols-[1fr_1fr_auto] gap-3 items-center"><div><div className={`text-2xl font-black ${procurement.action === 'BUY NOW' ? 'text-red-400' : procurement.action === 'WAIT' ? 'text-[#00FF41]' : 'text-[#F27D26]'}`}>{procurement.action}</div><div className="text-[8px] text-gray-600 mt-1">{quantity.toLocaleString()} MT PROCUREMENT PLAN</div></div><div className="grid grid-cols-3 gap-2"><Box label="BUY NOW" value={`${procurement.buyNowQuantityMt.toLocaleString()} MT`}/><Box label="WAIT" value={`${procurement.waitQuantityMt.toLocaleString()} MT`}/><Box label="LANDED" value={money(procurement.landedFreightCostUsd, 0)}/></div><button onClick={onNavigate} className="border border-[#333] hover:border-[#F27D26] text-[#F27D26] px-4 py-3 text-[9px] font-bold">OPEN PROCUREMENT →</button></div>;
const DecisionInspector: React.FC<{ integrated: ReturnType<typeof buildIntegratedDecision>; lane: FreightLane; quantity: number; onNavigate: () => void }> = ({ integrated, lane, quantity, onNavigate }) => <div className="grid lg:grid-cols-[1fr_1.5fr_auto] gap-4 items-center"><div><div className={`text-3xl font-black ${integrated.action === 'FIX NOW' ? 'text-red-400' : integrated.action === 'WAIT' ? 'text-[#00FF41]' : 'text-[#F27D26]'}`}>{integrated.action}</div><div className="text-[8px] text-gray-600 mt-1">{quantity.toLocaleString()} MT • {lane.code}</div></div><div className="space-y-2">{integrated.explanation.slice(0, 3).map((item, index) => <div key={index} className="flex gap-2 items-start text-[8px] text-gray-500"><CheckCircle2 className="w-3 h-3 text-[#F27D26] shrink-0 mt-0.5"/>{item}</div>)}</div><button onClick={onNavigate} className="border border-[#333] hover:border-[#F27D26] text-[#F27D26] px-4 py-3 text-[9px] font-bold">OPEN CHARTER →</button></div>;
const Box: React.FC<{ label: string; value: string }> = ({ label, value }) => <div className="border border-[#222] bg-[#0b0b0b] p-2"><div className="text-[7px] text-gray-700">{label}</div><div className="text-white text-[10px] font-black mt-1 truncate">{value}</div></div>;
